name = "FiniteVolumeFluid"
uuid = "c9d7ee53-733f-47f3-9b0b-71afcd20a75b"
authors = ["iamzhtr@hotmail.com"]
version = "0.1.0"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
